#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstRunComplete ]; then
  exit 0
fi

echo "Running Jackett first run setup..."

# Add user and group
addgroup --system --gid ${JACKETT_GID:-2000} jackett
adduser --system --home /config --shell /sbin/nologin --no-create-home --uid ${JACKETT_UID:-2000} --ingroup jackett --disabled-password --disabled-login jackett

# Set some sane defaults if there's no config file yet
if [ ! -f /config/ServerConfig.json ]; then
  cp /ServerConfig.json /config/ServerConfig.json
fi

# Update ownership of dirs we need to write to
chown -R jackett:jackett /config /data /opt/Jackett

touch /.firstRunComplete
echo "Jackett first run setup complete"
